# Generated by Django 4.1.9 on 2023-05-08 16:45

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(default=app.models.generate_random_string, max_length=250, primary_key=True, serialize=False)),
                ('date_submitted', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owners', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name_match_flag', models.CharField(default='NAN', max_length=255)),
                ('credit_score', models.CharField(default='NAN', max_length=255)),
                ('name_of_business', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('legal_business_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dba', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('suite', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('legal_entry', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state_inc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('federal_tax_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_business_started', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('years_at_location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('number_of_locations', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('length_of_ownership', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state_of_inc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('legal_entity', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_home_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_zip', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_ssn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_percentage_of_ownership', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_dob', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gross_monthly_sales', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('type_of_product_sold', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('has_open_cash_advances', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('has_used_cash_advance_plan_before', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('using_money_for', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description_of_business', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('advanced_price', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('commission_price', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('percentage', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('factor', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_fee', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payback', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('term', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payment', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('net_funding_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(default=app.models.generate_random_string, max_length=250)),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=2550, null=True)),
                ('starring', models.CharField(blank=True, default='', max_length=350, null=True)),
                ('users_cash_advance', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(default='Submited', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files/')),
                ('pdf_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_deposit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfFiles', to='app.application')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPDFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files/')),
                ('pdf_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_deposit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationPDFs', to='app.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='app.status'),
        ),
    ]
