# Generated by Django 4.1.9 on 2023-05-07 14:36

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(default=app.models.generate_random_string, max_length=250, primary_key=True, serialize=False)),
                ('date_submitted', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name_of_business', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('legal_business_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owners', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('users_cash_advance', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('have_cash_advance', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dba', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('suite', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('legal_entry', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state_inc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_home_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_zip', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_ssn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_percentage_of_ownership', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_dob', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('federal_tax_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state_of_inc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('legal_entity', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_business_started', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gross_monthly_sales', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('type_of_product_sold', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('has_open_cash_advances', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('has_used_cash_advance_plan_before', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('using_money_for', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description_of_business', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('length_of_ownership', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('years_at_location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('credit_score', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_deposit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name_match_flag', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('advanced_price', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('commission_price', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(default=app.models.generate_random_string, max_length=250)),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=2550, null=True)),
                ('starring', models.CharField(blank=True, default='', max_length=350, null=True)),
                ('users_cash_advance', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(default='Submited', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files/')),
                ('pdf_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_deposit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfFiles', to='app.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPDFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files/')),
                ('pdf_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_deposit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ending_bal_amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationPDFs', to='app.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='app.status'),
        ),
    ]
