# Generated by Django 4.1.9 on 2023-05-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedapplication',
            old_name='submitted_application_id',
            new_name='submittedApplication_id',
        ),
    ]
