# Generated by Django 4.1.9 on 2023-05-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='begin_bal_amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='begin_bal_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ending_bal_amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ending_bal_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='have_cash_advance',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_deposit',
        ),
        migrations.RemoveField(
            model_name='application',
            name='users_cash_advance',
        ),
        migrations.AddField(
            model_name='application',
            name='factor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='net_funding_amount',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='number_of_locations',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payback',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='percentage',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='term',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='total_fee',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
