# Generated by Django 4.1.9 on 2023-05-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dele',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_name_match_flag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='credit_score',
            field=models.CharField(default='', max_length=255),
        ),
    ]
